version: "3.4"

services:
  middleman:
    image: "openjdk:11"
    restart: always
    ports:
      - 8084:8080
    volumes:
      - ./:/work
    working_dir: /work
    command: java -jar /work/middleman-standalone-1.0.0-SNAPSHOT-jar-with-dependencies.jar 8080 /middleman2
